from apps.staff.permissions.item_image_permission import ItemImagePermission as ItemImagePermission
from apps.staff.permissions.item_permission import ItemPermission as ItemPermission
from apps.staff.permissions.occupation_permission import OccupationPermission as OccupationPermission
from apps.staff.permissions.order_permission import OrderPermission as OrderPermission
from apps.staff.permissions.restaurant_permission import RestaurantPermission as RestaurantPermission
from apps.staff.permissions.restaurant_user_permission import RestaurantUserPermission as RestaurantUserPermission
from apps.staff.permissions.table_permission import TablePermission as TablePermission
